export const ADICIONAR_PROJETO = 'ADICIONAR_PROJETO'
export const ALTERAR_PROJETO = 'ALTERAR_PROJETO'
export const EXCLUIR_PROJETO = 'EXCLUIR_PROJETO'
export const DEFINIR_PROJETOS = 'DEFINIR_PROJETOS'

export const DEFINIR_TAREFAS = 'DEFINIR_TAREFAS'
export const ADICIONAR_TAREFA = 'ADICIONAR_TAREFA'
export const ALTERAR_TAREFA = 'ALTERAR_TAREFA'

export const NOTIFICAR = 'NOTIFICAR'